name: Bug report
description: Report a reproducible issue
title: "[Bug] "
labels:
  - bug
body:
  - type: input
    id: environment
    attributes:
      label: Environment
      description: macOS version + shell
      placeholder: "macOS 15, zsh 5.9"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run ...
        2. Run ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior/output
    validations:
      required: true
